function outcome() {
	return random([
		"increase product quality",
		"identify pain points",
		"increase test automation",
		"benchmark system performance",
		"increase ROI",
		"identify long lasting test strategies",
		"make use of best practices",
		"change the game plan",
		"develop a 200 page test plan",
		"go viral in social media channels",
		"enhance user experience",
		"reduce system leverage",
		"provide 100% code coverage",
		"foster new paradigms in testing",
		"avoid assumption making",
		"mitigate 100% product risk",
		"increase documentation quality",
		"accurately estimate testing effort",
		"cross-pollinate ideas between underpowered disciplines",
		"increase systemic innovation and take entrepreneurial action",
		"encourage jazz-like improvisation within a guiding structure",
		"create a mindset of creative dissatisfaction to reduce resistance to change",
		"develop a automate-everything innovation strategy",
		"achieve a 100% test case pass rate",
		"lower combinatorial impairment",
		"achieve ultimate GUI atumation god-like status",
	]);
}
