function testing_technique() {
	return random([
		"functional testing",
		"boundary value analysis",
		"usability testing",
		"security testing",
		"automation testing",
		"brainstorming",
		"manual testing",
		"user acceptance testing",
		"system integration testing",
		"system testing",
		"heuristic evaluation",
		"use case analysis",
		"performance testing",
		"state analysis",
		"equivalence partitioning",
		"risk based testing",
		"risk analysis",
		"error testing",
		"pair testing",
		"static analysis",
		"exploratory testing",
		"critical thinking",
		"factory testing",
		"agile testing",
		"context-driven testing",
		"contextual enquiry",
		"gamification",
		"concept model",
		"mental model",
		"healthcheck",
		"process mapping",
		"accessibility testing",
		"acceptance testing",
		"action word driven testing",
		"attack based testing",
		"audit",
		"back-to-back testing",
		"black box testing",
		"best practice testing",
		"big bang testing",
		"bottom up testing",
		"boundary value testing",
		"branch condition combination testing",
		"bug reporting",
		"metrics reporting",
		"record and playback automation",
		"cause-effect graphing",
		"decision tabling",
		"clear box testing",
		"code coverage analysis",
		"exhaustive testing",
		"condition combination testing",
		"consultative testing",
		
	]);
}
